# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def main():
	# initialize first two values
	n_0 = 1
	n_1 = 2

	# track current sum
	current_sum = 2

	while n_1 < 4000000:
		new_number = n_1 + n_0
		if new_number % 2 == 0:
			current_sum += new_number

		# move everything up
		n_0 = n_1
		n_1 = new_number

	print(current_sum)




if __name__ == "__main__":
	main()